- hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
